apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      containers:
      - name: authelia
        image: authelia/authelia:4.37.5
        ports:
        - containerPort: 9091
        envFrom:
        - secretRef:
            name: auth-secrets
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: authelia-config
      - name: data
        persistentVolumeClaim:
          claimName: authelia-data
