apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lldap
  template:
    metadata:
      labels:
        app: lldap
    spec:
      containers:
      - name: lldap
        image: nitnelave/lldap:latest
        ports:
        - containerPort: 3890
        - containerPort: 17170
        envFrom:
        - secretRef:
            name: auth-secrets
        env:
        - name: UID
          value: "1000"
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lldap-data